#!/usr/bin/env node
/**
 * Renders every email this kit can send, against a fixed sample, into
 * docs/EMAILS.md. A partner can then read the whole thing before installing,
 * and any change to the copy shows up as a readable diff in review.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { plan } from '../kits/uk-accountancy/04-invoice-payment-chasing/src/core/plan.js';
import { buildDigest } from '../kits/uk-accountancy/04-invoice-payment-chasing/src/core/copy.js';

const KIT = join(dirname(fileURLToPath(import.meta.url)), '..',
  'kits', 'uk-accountancy', '04-invoice-payment-chasing');

const config = {
  dryRun: false,
  firmName: 'Example Accountants Ltd',
  senderName: 'Accounts',
  senderEmail: 'accounts@exampleaccountants.co.uk',
  replyToEmail: 'accounts@exampleaccountants.co.uk',
  firmPhone: '01234 567890',
  signOffName: 'Sam Patel',
  paymentInstructions: 'Bank transfer to Example Accountants Ltd, sort code 00-00-00,\naccount 12345678. Please quote the invoice number as the reference.',
  mentionLpcda: true,
};

const row = (n, client, email, type, amount, due, stage = '') => ({
  row_number: n, 'Invoice Number': `INV-${n + 1000}`, Client: client,
  'Client Email': email, 'Client Type': type, 'Amount GBP': amount,
  'Due Date': due, Status: 'Unpaid', 'Last Chase Stage': stage,
  'Last Chased On': stage ? '2026-08-20' : '', 'Activation Date': '2026-06-01',
});

const cases = [
  ['Friendly reminder, business client',
    'Ten days overdue. The first contact any client gets. No mention of interest at this stage.',
    [row(2, 'Borough Cafe Ltd', 'ap@boroughcafe.co.uk', 'Business', '480.50', '2026-09-05')]],
  ['Friendly reminder, individual client',
    'The same stage for a client marked Individual. Identical, because nothing statutory applies yet.',
    [row(3, 'Jane Example', 'jane@example.com', 'Individual', '320.00', '2026-09-05')]],
  ['Firm reminder, business client',
    'Thirty-two days overdue, already sent a friendly reminder. This is where the Late Payment of Commercial Debts (Interest) Act paragraph appears, with the fixed sum for this debt size.',
    [row(4, 'Castle Motors Ltd', 'ap@castlemotors.co.uk', 'Business', '1250.00', '2026-08-14', 'friendly')]],
  ['Firm reminder, individual client',
    'The same stage for an individual. The Act covers business debts only, so that paragraph is absent.',
    [row(5, 'John Example', 'john@example.com', 'Individual', '1250.00', '2026-08-14', 'friendly')]],
  ['Final notice, after earlier reminders',
    'Sixty-seven days overdue, and this system sent the earlier reminders, so referring to them is accurate.',
    [row(6, 'Delta Design Ltd', 'studio@deltadesign.co.uk', 'Business', '12000.00', '2026-07-10', 'firm')]],
  ['Final notice on a client with several invoices',
    'One email, every invoice listed, pitched at the tone the oldest debt warrants. The client is not sent three separate emails.',
    [row(7, 'Multi Ltd', 'ap@multi.co.uk', 'Business', '100.00', '2026-09-05'),
     row(8, 'Multi Ltd', 'ap@multi.co.uk', 'Business', '200.00', '2026-08-05'),
     row(9, 'Multi Ltd', 'ap@multi.co.uk', 'Business', '2400.00', '2026-07-05')]],
];

const today = '2026-09-15';
const out = [
  '# Every email this kit can send',
  '',
  '_Generated by `scripts/render-emails.js`. Do not edit by hand; change the copy',
  `in \`src/core/copy.js\` and regenerate. Rendered against a sample practice on ${today}._`,
  '',
  'Read this before installing. It is the whole of what a client will ever receive.',
  '',
];

for (const [title, note, rows] of cases) {
  const r = plan({ rows, today, config });
  out.push(`## ${title}`, '', note, '');
  if (!r.actions.length) {
    out.push('_No email is sent in this case._', '',
      ...r.skipped.map((s) => `- ${s.invoiceNumber}: ${s.reason}`), '');
    continue;
  }
  for (const a of r.actions) {
    out.push('```text', `To:      ${a.realRecipient}`, `Subject: ${a.subject}`, '', a.body, '```', '');
  }
}

// The internal preview.
const all = cases.flatMap(([, , rows]) => rows).map((r, i) => ({ ...r, row_number: i + 2 }));
const previewPlan = plan({ rows: all, today, config });
const digest = buildDigest({
  actions: previewPlan.actions, skipped: previewPlan.skipped,
  runDate: today, config, holdUrl: 'https://n8n.example.co.uk/webhook/kit04-hold-today',
});
out.push('## The 08:30 preview, sent to the practice',
  '', 'Not a client email. This is what the practice sees 30 minutes before anything goes out.', '',
  '```text', `To:      ${config.senderEmail}`, `Subject: ${digest.subject}`, '', digest.body, '```', '');

writeFileSync(join(KIT, 'docs', 'EMAILS.md'), `${out.join('\n')}\n`);
console.log('wrote docs/EMAILS.md');
